---
version: '3'

services:
  db:
    image: postgres
    # environment:
    #   - POSTGRES_DB=bth-app
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin4:
    image: dpage/pgadmin4:latest
    volumes:
      - ./pgadmin/pg:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "5050:80"

  # backend:
  #   image: bth-go-backend
  #   build:
  #     context: api
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - GIN_MODE=debug
  #     # - GIN_MODE=release
  #     - POSTGRES_NAME=bth-app
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - DB_HOST=db
  #   # env_file:
  #   #   - .env
  #   depends_on:
  #     - db
