---
name: Gofumpt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies
        run: go install mvdan.cc/gofumpt@latest

      - name: Gofumpt
        run: test -z "$(gofumpt -d -e . | tee /dev/stderr)"
