---
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  revive-linter:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run Revive Linter
      uses: docker://morphy/revive-action:v2
      with:
        config: revive-conf.toml
