---
name: Revive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api
    steps:
    - uses: actions/checkout@v3

    - name: Run Revive Linter
      uses: docker://morphy/revive-action:v2
      with:
        config: ../../backend/api/revive/config.toml
